#!/bin/bash
##  Conda安装与配置
# 下载最新版Anaconda
wget https://repo.anaconda.com/archive/Anaconda3-2024.06-1-Linux-x86_64.sh

# 执行安装脚本
sh Anaconda3-2024.06-1-Linux-x86_64.sh 

# 配置环境变量
echo 'export PATH=$HOME/anaconda3/bin:$PATH' >> ~/.bashrc
source ~/.bashrc

# 更新Conda
conda update conda

# 验证安装
conda --version

