#!/bin/bash
## 生物信息软件安装
# 质控软件安装（fastqc、trimmomatic、multiqc）
conda install fastqc trimmomatic multiqc

# 组装软件安装（SPAdes）
wget https://github.com/ablab/spades/releases/download/v4.0.0/SPAdes-4.0.0-Linux.tar.gz
tar -zxvf SPAdes-4.0.0-Linux.tar.gz
rm SPAdes-4.0.0-Linux.tar.gz  # 删除压缩包节省空间
vim ~/.bashrc
export PATH=$PATH:$HOME/download/SPAdes-4.0.0-Linux/bin

# 评价软件安装(quast、busco)
conda install quast

conda create --name busco
conda activate busco
conda install busco

# 重复序列注释(repeatmasker)
conda install repeatmasker

# denovo预测基因结构（augustus）
wget http://augustus.gobics.de/binaries/augustus.2.5.5.tar.gz
tar -zxvf augustus.2.5.5.tar.gz
rm augustus.2.5.5.tar.gz
cd augustus.2.5.5/src
make
vim ~/.bashrc
export AUGUSTUS_CONFIG_PATH=$HOME/download/augustus.2.5.5/config
export PATH=$PATH:$HOME/download/augustus.2.5.5/bin

# 功能注释（blast）（NR、KEGG、Swiss-Prot、TrEMBL）
wget https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.16.0+-x64-linux.tar.gz
tar -zxvf ncbi-blast-2.16.0+-x64-linux.tar.gz
rm ncbi-blast-2.16.0+-x64-linux.tar.gz
cd ncbi-blast-2.16.0+
pwd
vim ~/.bashrc
export PATH=$PATH:$HOME/download/blast/bin
export BLASTDB=$HOME/download/blast/db

# 功能注释（interproscan）（GO）
wget https://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/5.73-104.0/interproscan-5.73-104.0-64-bit.tar.gz
wget https://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/5.73-104.0/interproscan-5.73-104.0-64-bit.tar.gz.md5
md5sum -c interproscan-5.73-104.0-64-bit.tar.gz.md5
tar -pxvzf interproscan-5.73-104.0-64-bit.tar.gz
rm interproscan-5.73-104.0-64-bit.tar.gz*
cd interproscan-5.73-104.0
python3 setup.py -f interproscan.properties
./interproscan.sh
